name: Deploy Dist folder 
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
              # run: |
              #   echo "Cloning repo"
              #   echo "${{toJson(github)}}"
              #   git clone https://github.com/${{github.repository}}.git myfiles
              #   cd myfiles && ls
            - name: setup node js
              uses: actions/setup-node@v4
              with: 
                node-version: 22
            - name: Cache dependencies
              uses: actions/cache@v4
              id: cache
              with:
                path: path/to/dependencies
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm install
            - name: Run Tests
              run: npm run test
            - name: Completed job
              run: echo "Test job was success"

    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: setup node js
          uses: actions/setup-node@v4
          with: 
            node-version: 22
        - name: Cache dependencies
          uses: actions/cache@v4
          id: cache
          with:
            path: path/to/dependencies
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - name: Install Dependencies
          if: steps.npm-cache.outputs.cache-hit != 'true'
          run: npm install
        - name: build project
          run: npm run build
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Dist
          run: echo 'Deployment completed'


        
            